// Generated by CoffeeScript 1.4.0
var sendMsg, serverprocesscheck;

exports.main = function(req, res) {
  req.check_result = '';
  return async.series([
    function(callBack) {
      return serverProcessCheck(req, callBack);
    }, function(callBack) {
      return sendMsg(req, res, callBack);
    }
  ], function(err, result) {
    if (err) {
      throw err;
    }
    return console.log("" + req.ip + " -> submit all done. " + result);
  });
};

serverprocesscheck = function(req, callback) {
  req.check_result = process.env["worker_state"];
  return callback(null, 1);
};

sendMsg = function(req, res, callback) {
  res.send(req.check_result);
  return callBack(null, 2);
};
