// Generated by CoffeeScript 1.4.0

module.exports = function(option) {
  var app, database;
  app = option.app;
  database = option.database;
  app.get('/request_jadge', function(req, res, next) {
    var jadge;
    jadge = require('./jadge_source');
    return jadge.main(req, res, database);
  });
  return "controller is setup";
};
