// Generated by CoffeeScript 1.4.0

module.exports = function(options) {
  var columns, database, dbname, dbpass, dbuser, hostname, portnum, seq, seq_option, sequelize;
  sequelize = require('sequelize');
  dbname = 'pxp_lab';
  dbuser = 'root';
  dbpass = '29148931';
  hostname = 'localhost';
  portnum = 3306;
  seq = new sequelize(dbname, dbuser, dbpass, {
    host: hostname,
    port: portnum
  });
  database = new Object();
  seq_option = {
    timestamps: false,
    freezeTableName: true
  };
  database.seq = seq;
  columns = {
    userID: {
      type: sequelize.STRING,
      primaryKey: true
    },
    questionNo: sequelize.STRING,
    source: sequelize.TEXT,
    result: sequelize.STRING,
    time: {
      type: sequelize.DATE
    }
  };
  database.submitTable = seq.define("Submit_table", columns, seq_option);
  columns = {
    questionNo: {
      type: sequelize.STRING,
      primaryKey: true
    },
    answer: sequelize.TEXT,
    testcase: sequelize.TEXT
  };
  database.answerTable = seq.define('Answer_table', columns, seq_option);
  columns = {
    id: {
      type: sequelize.INTEGER,
      primaryKey: true
    },
    questionNo: {
      type: sequelize.STRING
    },
    userID: sequelize.STRING,
    source: sequelize.TEXT
  };
  database.submitQueueTable = seq.define('SubmitQueue_table', columns, seq_option);
  columns = {
    questionNo: {
      type: sequelize.STRING,
      primaryKey: true
    },
    userID: sequelize.STRING
  };
  database.correcterTable = seq.define('Correcter_table', columns, seq_option);
  console.log('Database is setup.');
  return database;
};
