// Generated by CoffeeScript 1.6.2
var AppConfig, LogConfig;

exports.AppConfig = AppConfig = (function() {
  var _engine, _keepExtention;

  _keepExtention = true;

  _engine = "ejs";

  function AppConfig(port, dir) {
    this.appDir = dir;
    this.port = port;
    this.tmpDir = "" + this.appDir + "/tmp";
    this.view = "" + this.appDir + "/views";
    this["public"] = "" + this.appDir + "/public";
  }

  AppConfig.prototype.getPort = function() {
    return this.port;
  };

  AppConfig.prototype.getView = function() {
    return this.view;
  };

  AppConfig.prototype.getPublic = function() {
    return this["public"];
  };

  AppConfig.prototype.getEngine = function() {
    return _engine;
  };

  AppConfig.prototype.upload = function() {
    return {
      uploadDir: this.tmpDir,
      isKeepExtensions: _keepExtention
    };
  };

  return AppConfig;

})();

exports.LogConfig = LogConfig = (function() {
  var _date, _size;

  _size = 1024 * 1024;

  _date = '-yyyy-MM-dd';

  function LogConfig(dir) {
    this.dir = dir;
  }

  LogConfig.prototype.getName = function() {
    return "" + this.dir + "/logs/pxp_log";
  };

  LogConfig.prototype.getSize = function() {
    return _size;
  };

  LogConfig.prototype.getStdout = function() {
    return false;
  };

  LogConfig.prototype.getPattern = function() {
    return _date;
  };

  LogConfig.prototype.getNolog = function() {
    return ['\\.css', '\\.js', '\\.gif', '\\.jpg', '\\.png'];
  };

  LogConfig.prototype.format = function() {
    return JSON.stringify({
      'method': ':method',
      'request': ':url',
      'status': ':status',
      'user-agent': ':user-agent'
    });
  };

  return LogConfig;

})();
