// Generated by CoffeeScript 1.6.2
module.exports = function(option) {
  var app, dataBase;

  app = option.app;
  dataBase = option.database;
  app.get('/', function(req, res, next) {
    console.log('test ------');
    return res.send('test');
  });
  app.get('/request_judge', function(req, res, next) {
    var judge;

    judge = require('./judge_source');
    return judge.main(req, res, dataBase);
  });
  return "controller is setup";
};
