// Generated by CoffeeScript 1.6.2
/* ------- Module dependencies. ------------
*/

var AppConfig, LogConfig, SessionConfig, app, cluster, config, engine, express, http, log4js, mongoose, node_config, server, sio;

express = require('express');

cluster = require('cluster');

engine = require('ejs-locals');

log4js = require('crafity-log4js');

http = require('http');

sio = require('socket.io');

mongoose = require('mongoose');

app = express();

/* ------- Class ---------------------------
*/


node_config = require('../node-config.json');

config = require("../config");

AppConfig = new config.AppConfig(3000, __dirname);

LogConfig = new config.LogConfig(__dirname);

SessionConfig = (function() {
  var _access, _connect, _interval, _limit, _path, _secret, _sessionstore;

  function SessionConfig() {}

  _connect = require('connect');

  _sessionstore = require('session-mongoose')(express);

  _path = 'mongodb://localhost/lab_sessions';

  _access = false;

  _interval = 60 * 60 * 1000 * 24;

  _limit = new Date(Date.now() + _interval);

  _secret = node_config.session.session_secret;

  SessionConfig.getMemoryStore = function() {
    return _sessionstore;
  };

  SessionConfig.getSecret = function() {
    return _secret;
  };

  SessionConfig.getStore = function() {
    return new _sessionstore({
      secret: _secret,
      url: _path,
      interval: _interval
    });
  };

  SessionConfig.getCookie = function() {
    return {
      httpOnly: _access,
      maxAge: _limit
    };
  };

  return SessionConfig;

})();

/* ------- middleware ------------------------
*/


app.configure(function() {
  var logger;

  app.set('port', AppConfig.getPort());
  app.set('views', AppConfig.getView());
  app.engine('ejs', engine);
  app.set('view engine', AppConfig.getEngine());
  app.use(express.favicon());
  logger = log4js.getLogger('file');
  log4js.configure({
    appenders: [
      {
        'type': 'console'
      }, {
        'type': 'file',
        'filename': LogConfig.getName(),
        'maxLogSize': LogConfig.getSize(),
        'pattern': LogConfig.getPattern(),
        'category': 'console'
      }
    ],
    replaceConsole: LogConfig.getStdout()
  });
  app.use(log4js.connectLogger(logger, {
    nolog: LogConfig.getNolog(),
    format: LogConfig.format()
  }));
  app.use(express.compress());
  app.use(express.bodyParser(AppConfig.upload()));
  app.use(express.cookieParser(SessionConfig.getSecret()));
  app.use(express.session({
    secret: SessionConfig.getSecret(),
    store: SessionConfig.getStore(),
    cookie: SessionConfig.getCookie()
  }));
  app.use(express.methodOverride());
  app.use(express["static"](AppConfig.getPublic()));
  return console.log("app opption setup.");
});

/* ------- create httpServer.-----------------
*/


if (cluster.isMaster) {
  server = http.createServer(app);
  server.listen(app.get('port'), function() {
    var database, database_root, socketServer, timer_id;

    console.log("Master Server listening on " + (app.get('port')));
    database_root = "../db/database";
    database = require(database_root)({
      config: node_config
    });
    socketServer = require("" + __dirname + "/routes/socket_server");
    console.log("" + (socketServer.setup(app, http, sio, SessionConfig, mongoose)));
    return timer_id = setTimeout(function() {
      var controller;

      controller = "" + __dirname + "/routes/controller";
      return console.log("" + (require(controller)({
        app: app,
        database: database
      })));
    }, 100);
  });
}

/* ------- Error. -----------------------------------------
*/


process.on('uncaughtException', function(err) {
  console.log("err >  " + err);
  return console.error("uncaughtException >  " + err.stack);
});
