// Generated by CoffeeScript 1.4.0
var destroy_session, rooting;

exports.main = function(req, res) {
  var async, time;
  async = require('async');
  time = 100;
  return async.series([
    function(callback) {
      destroy_session(req);
      return setTimeout(function() {
        return callback(null, 1);
      }, time);
    }, function(callback) {
      rooting(req, res);
      return setTimeout(function() {
        return callback(null, 2);
      }, time);
    }
  ], function(err, result) {
    if (err) {
      throw err;
      res.redirect('/');
    }
    return console.log("destroy all done. " + result);
  });
};

destroy_session = function(req) {
  return req.session.destroy();
};

rooting = function(req, res) {
  return res.redirect('/');
};
