// Generated by CoffeeScript 1.6.2
var get_submits, response;

exports.main = function(req, res, database) {
  var async, ip_address, time;

  async = require('async');
  ip_address = req.ip;
  time = 300;
  req.ranking = req.ranking;
  req.resJSON = req.resJSON;
  async.series([
    function(callback) {
      get_submits(req, database);
      return setTimeout(function() {
        return callback(null, 1);
      }, time);
    }, function(callback) {
      response(req, res);
      return setTimeout(function() {
        return callback(null, 2);
      }, time);
    }
  ], function(err, result) {
    if (err) {
      throw err;
      res.redirect('/');
    }
    return console.log("get_ranking all done. " + result);
  });
  return console.log("get_ranking ---------- " + ip_address);
};

get_submits = function(req, database) {
  return database.Submit_table.findAll({
    order: "time DESC",
    limit: 100
  }).success(function(calum) {
    var i, len, _results;

    if ((calum != null)) {
      i = 0;
      len = calum.length;
      _results = [];
      while (i < len) {
        req.ranking[i] = {
          volumeNo: calum[i].num,
          username: calum[i].register,
          result: calum[i].jadge,
          time: calum[i].time
        };
        _results.push(i++);
      }
      return _results;
    }
  });
};

response = function(req, res) {
  return res.json(req.ranking);
};
