// Generated by CoffeeScript 1.6.2
var getSubmits, sendRanking;

exports.main = function(req, res, dataBase) {
  var async, ip_address, submitTable;

  async = require('async');
  ip_address = req.ip;
  req.ranking = [];
  submitTable = dataBase.submitTable;
  async.series([
    function(callBack) {
      return getSubmits(req, submitTable, callBack);
    }, function(callBack) {
      return sendRanking(req, res, callBack);
    }
  ], function(err, result) {
    if (err) {
      throw err;
      res.redirect('/');
    }
    return console.log("get_ranking all done. " + result);
  });
  return console.log("get_ranking ---------- " + ip_address);
};

getSubmits = function(req, submitTable, callBack) {
  return submitTable.findAll({
    order: "time DESC",
    limit: 100
  }).success(function(columns) {
    var column, rank, _i, _len;

    for (rank = _i = 0, _len = columns.length; _i < _len; rank = ++_i) {
      column = columns[rank];
      req.ranking[rank] = {
        questionNo: column.questionNo,
        userID: column.userID,
        result: column.result,
        time: column.time
      };
    }
    return callBack(null, 1);
  }).error(function(error) {
    return console.log("submitTable err > " + error);
  });
};

sendRanking = function(req, res, callBack) {
  res.json(req.ranking);
  return callBack(null, 2);
};
