// Generated by CoffeeScript 1.4.0
var getSubmits, sendRanking;

exports.main = function(req, res, dataBase) {
  var async, ip_address, submitTable;
  async = require('async');
  ip_address = req.ip;
  req.ranking = [];
  submitTable = dataBase.submitTable;
  async.series([
    function(callBack) {
      return getSubmits(req, submitTable, callBack);
    }, function(callBack) {
      return sendRanking(req, res, callBack);
    }
  ], function(err, result) {
    if (err) {
      throw err;
      res.redirect('/');
    }
    return console.log("get_ranking all done. " + result);
  });
  return console.log("get_ranking ---------- " + ip_address);
};

getSubmits = function(req, submitTable, callBack) {
  return submitTable.findAll({
    order: "time DESC",
    limit: 100
  }).success(function(columns) {
    var i, len;
    if ((columns != null)) {
      i = 0;
      len = columns.length;
      while (i < len) {
        req.ranking[i] = {
          questionNo: columns[i].questionNo,
          userID: columns[i].userID,
          result: columns[i].result,
          time: columns[i].time
        };
        i++;
      }
    }
    return callBack(null, 1);
  }).error(function(error) {
    return console.log("submitTable err > " + error);
  });
};

sendRanking = function(req, res, callBack) {
  res.json(req.ranking);
  return callBack(null, 2);
};
